# Generated by Django 6.0.1 on 2026-02-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sellerverification_is_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
