# Generated by Django 6.0.2 on 2026-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_payment_type_payment_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('RENT', 'Location'), ('BUY', 'Achat')], default='RENT', max_length=10),
        ),
    ]
