# Generated by Django 6.0.2 on 2026-03-27 05:12

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_payment_type'),
        ('properties', '0003_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('contract_type', models.CharField(choices=[('RENT', 'Contrat de Location'), ('BUY', 'Contrat de Vente')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_seller', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='core.transaction')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
