# Generated by Django 6.0.2 on 2026-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
