# Generated by Django 6.0.2 on 2026-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingStatusModel',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], default='FOR_SALE', max_length=20),
        ),
    ]
